SCALE Job started on Wed 22/07/2020 08:56:03
With Host name Milos-Atzs-MacBook-Pro
working directory /var/folders/l0/rb8l41m171783kwrt2srjnlw0000gn/T/scale.goldilockczech.3628
and process id 3628.
Input file named /Users/goldilockczech/Documents/Research/Fuel-Cycle-Wastes/nwpy/notebooks/output/eg13/1/eg13-1_glass.inp
and output file named /Users/goldilockczech/Documents/Research/Fuel-Cycle-Wastes/nwpy/notebooks/output/eg13/1/eg13-1_glass.out
##########################################################
